AWSTemplateFormatVersion: "2010-09-09"
Description: Builds web and API server resources (for dev environment)

Resources:
  WebSecurityGroupDev:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - '{{resolve:secretsmanager:web-stack-dev:SecretString:S3RootBucket}}'
          - ".s3."
          - '{{resolve:secretsmanager:web-stack-dev:SecretString:S3RootBucketRegion}}'
          - ".amazonaws.com/cfn-templates/ec2/create-security-group-web.yaml"
      Parameters:
        GroupName: "web-server-dev-security-group"
        GroupDescription: "AWS EC2 Security Group for web-stack-dev"
        VpcId: '{{resolve:secretsmanager:web-stack-dev:SecretString:VpcId}}'

  ApiSecurityGroupDev:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - '{{resolve:secretsmanager:web-stack-dev:SecretString:S3RootBucket}}'
          - ".s3."
          - '{{resolve:secretsmanager:web-stack-dev:SecretString:S3RootBucketRegion}}'
          - ".amazonaws.com/cfn-templates/ec2/create-security-group-api.yaml"
      Parameters:
        GroupName: "api-server-dev-security-group"
        GroupDescription: "AWS EC2 Security Group for api-stack-dev"
        NetworkPublicIp: '{{resolve:secretsmanager:web-stack-dev:SecretString:NetworkPublicIp}}'
        SecurityGroupWeb: !GetAtt WebSecurityGroupDev.Outputs.NewWebSecurityGroupId
        VpcId: '{{resolve:secretsmanager:web-stack-dev:SecretString:VpcId}}'

  WebEc2InstanceDev:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - '{{resolve:secretsmanager:web-stack-dev:SecretString:S3RootBucket}}'
          - ".s3."
          - '{{resolve:secretsmanager:web-stack-dev:SecretString:S3RootBucketRegion}}'
          - ".amazonaws.com/cfn-templates/ec2/create-ec2-instance.yaml"
      Parameters:
        KeyPairName: "test-ec2-instances"
        InstanceName: "web-server-dev"
        InstanceType: "t2.micro"
        AmiId: "ami-0cf2b4e024cdb6960"
        SecurityGroupId: !GetAtt WebSecurityGroupDev.Outputs.NewWebSecurityGroupId
        SubnetId: '{{resolve:secretsmanager:web-stack-dev:SecretString:SubnetId}}'
        UserData:
          "Fn::Base64": !Sub |
            #!/bin/bash
            apt-get update && echo "I'm the dev web server!"

  ApiEc2InstanceDev:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    Properties:
      TemplateURL: "https://{{resolve:secretsmanager:web-stack-dev:SecretString:S3RootBucket}}.s3.{{resolve:secretsmanager:web-stack-dev:SecretString:S3RootBucketRegion}}.amazonaws.com/cfn-templates/ec2/create-ec2-instance.yaml"
      Parameters:
        KeyPairName: "test-ec2-instances"
        InstanceName: "api-server-dev"
        InstanceType: "t2.micro"
        AmiId: "ami-0cf2b4e024cdb6960"
        SecurityGroupId: !GetAtt ApiSecurityGroupDev.Outputs.NewApiSecurityGroupId
        SubnetId: '{{resolve:secretsmanager:web-stack-dev:SecretString:SubnetId}}'
        UserData:
          "Fn::Base64": !Sub |
            #!/bin/bash
            apt-get update && echo "I'm the dev API server!"