AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for React site hosting with S3, CloudFront and Route53


Parameters:
  HostedZoneId:
    Type: String
    Description: The Route53 Hosted Zone ID for the domain
  
  DomainName:
    Type: String
    Description: The domain name for the React site

  CertificateArn:
    Type: String
    Description: The ARN of the SSL certificate for the domain


Resources:
  ReactSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::Region}-${AWS::AccountId}-${DomainName}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  ReactOac:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: ReactSiteOac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReactSiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub '${ReactSiteBucket.Arn}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${ReactSiteDistribution}'

  CloudFrontOai:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access Identity for React S3 Bucket

  ReactSiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt ReactSiteBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref ReactOac
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Enabled: true

  ReactSiteRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ReactSiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 #NOTE: CloudFront Hosted Zone ID for us-east-1


Outputs:
  WebsiteURL:
    Description: URL of the React site
    Value: !Sub "http://${ReactSiteDistribution.DomainName}"