#!/bin/bash

## Clean up downstream resources generated by create-cicd-pipeline.yaml for testing purposes. This specific script
## doesn't need to do anything, but needs to exist for the "web-stack-react" project.

echo "$(date) :: Running sub-script:"
echo $BASH_SOURCE
echo

if [[ "${0}" == "${BASH_SOURCE}" ]]; then
  echo "$(date) :: FATAL - This script must be sourced by 'src/aws/cleanup-cicd-pipeline.sh', not executed directly..."
  echo

  exit 1
else
  echo "$(date) :: Proceeding with sub-script..."
  echo
fi

echo "$(date) :: Nothing to do here, proceed with main cleanup..."
echo